### ISSUE TITLE
Class DDDS - drive.list('txt')

### ISSUE THREAD

**Issue by srigaut** [Jackfn96/3DS#13]
Would it be possible to avoid looking into the 'échantillon' folder?
Otherwise I'm getting the elements 'Signaux HRV Garmin.txt' and 'Signaux HRV multi-capteurs.txt' which will not be useful.

**Comment by JanKrl** [comment]
Will this folder be not used at all, or only for specific cases? I can modify `get_children_folders_id(self)` to `get_children_folders_id(self, exclude=None)` where you would be able to specify folder names not to be included in search space.

**Comment by srigaut** [comment]
I think it is a sample of 1 measure (1 video, 1 annotation, 1 HRV (both multi and Garmin sensors)), already available in the dataset. We will probably never use it.
In any case, I like the feature you suggested => let's do it like that!
Thanks

**Comment by JanKrl** [comment]
Ah, I see. it's a folder with sample data. Agree, we can exclude `échantillon` folder from search.
But I'll also implement `get_children_folders_id(self, exclude=None)`. It might be useful and only a few lines of code.

**Comment by srigaut** [comment]
Agreed - thanks!
